### ISSUE TITLE
i can't change color of text

### ISSUE THREAD

**Issue by ahmedalkhashab** [jakob-grabner/Circle-Progress-View#1]
Hi 

i try to change color of text using:
setUnitColor & setTextColor 
but i can't 

what happened that Text color is same color of bar

note: i can change size of text using: 
setTextSize

 Regards

**Comment by jakob-grabner** [comment]
Make sure to call setupPaints(); after changing the text colors. Maybe I should add some more documentation to make this more clear.

**Comment by AniruddhaSingh** [comment]
Hi jakob-grabner,
Thanks for this awesome library. 
I was facing the same problem. setupPaints(); is working fine, but after call to this method text & unit size is random. Sometime its too small, sometime its normal. Please suggest some fix to this problem.

**Comment by jakob-grabner** [comment]
Please try the latest release. I fixed a few bugs. Also it is no longer necessary to call setupPaints().
