### ISSUE TITLE
How to change the inner circle background color?

### ISSUE THREAD

**Issue by anikdey** [jakob-grabner/Circle-Progress-View#103]
I want the inner circle to be white. How can i do that.

![Untitled](https://user-images.githubusercontent.com/6571502/67266985-3d959200-f4d3-11e9-9060-480a46144872.png)

**Comment by jakob-grabner** [comment]
Try

```
 <at.grabner.circleprogress.CircleProgressView
        CircleProgressView:cpv_fillColor="@color/primary" />
```
