### ISSUE TITLE
textMode attribute not working from xml

### ISSUE THREAD

**Issue by adennie** [jakob-grabner/Circle-Progress-View#13]
I think you need to declare it as format=integer

**Comment by jakob-grabner** [comment]
Works fine for me. What exactly does not work for you? You need to set it to one of: 
CircleProgressView:textMode="Percent"
CircleProgressView:textMode="Value"
CircleProgressView:textMode="Text"

But it shouldn't compile anyway if you enter something else (therefore enum instead of integer).

**Comment by adennie** [comment]
Ah, sorry, my bad.  I saw the `a.getInt()` in CircleProgressView.java and incorrectly inferred that it needed to be an integer value.
