### ISSUE TITLE
setBarColor not working

### ISSUE THREAD

**Issue by marcforn** [jakob-grabner/Circle-Progress-View#18]
Hi, 

I'm setting four colors for the gradient in that way:
    `customProgressBar.setBarColor(Color.RED, Color.BLUE, Color.GRAY, Color.GREEN);`
           `customProgressBar.spin();`

 but only shows the progress with degault color, no gradient.

What I'm doing wrong?

Thanks in advance

**Comment by jakob-grabner** [comment]
Hi,
setBarColor() should work fine the way you used it. But there is another color to set for the bar in spinning mode. So please use setSpinBarColor(); In spinning mode, currently only a single color is supported (no gradient). If you wanna use a gradient please let me know.

**Comment by marcforn** [comment]
OK, I thouhgt there was possible to set four colors in spining mode.

Thanks for the response
