### ISSUE TITLE
Borderless ring

### ISSUE THREAD

**Issue by swapps** [jakob-grabner/Circle-Progress-View#19]
Hi, is there a way to make the ring borderless, i would like it to use whole screen with no margin around it

**Comment by jakob-grabner** [comment]
Hi, actually there were some margin issues I didn't notice. Just fixed them, check out the newest commit.
 
	dependencies {
	        compile 'com.github.jakob-grabner:Circle-Progress-View:853b1b8aca'
	}

**Comment by swapps** [comment]
great, thanks so much for such a quick answer !!
