### ISSUE TITLE
Mask ImageView with Circular Progress View

### ISSUE THREAD

**Issue by groovedev** [jakob-grabner/Circle-Progress-View#2]
Hi jakob-grabner,

Can you tell me if it's possible to mask the Circular Progress View? Like this StackOverflow lays out?

http://stackoverflow.com/questions/31846237/android-mask-imageview-with-circular-progress-view

Thanks.

-- Rick

**Comment by jakob-grabner** [comment]
I think you should be able to achieve the transparent C with
semitransparent colors. But at the moment only a full circle is supported.
But I can take a look at custom start and end angles of the circle next
week.

Cheers,
Jakob
Am 06.08.2015 8:27 nachm. schrieb "Rick" <notifications@github.com>:

**Comment by groovedev** [comment]
Hi Jakob,

Thanks for the response.  I think start and end angles would be helpful,
but I'm not sure that would completely solve my problem.  What I want is to
have that specific letter C(logo) filled-in and mask out all outside areas.

So for example if the Circular Progress View was given a mask of the C, the
progress would only be visible in the logo mask.  Basically filling in the
C.

If you think it should currently work with the Circular Progress View, can
you provide an example?

Thanks for the help.

-- Rick

**Comment by jakob-grabner** [comment]
It is now possible to specify a masking bitmap by calling setClippingBitmap(Bitmap).

**Comment by groovedev** [comment]
Cool, even though mines is working great, I'll check yours out and give you
feedback.

-- Rick
