### ISSUE TITLE
All Attributes  not works

### ISSUE THREAD

**Issue by miladmofficial** [jakob-grabner/Circle-Progress-View#20]
what is current attributes are? "cpv_barWidth" are unknown for IDE

**Comment by jakob-grabner** [comment]
Hi,

please make sure to import the correct name space (xmlns:CircleProgressView="http://schemas.android.com/apk/res-auto") into your layout file. 
For an example see the [example app](https://github.com/jakob-grabner/Circle-Progress-View/blob/master/ExampleApp/src/main/res/layout/activity_main.xml)

**Comment by miladmofficial** [comment]
Thanks. it works
