### ISSUE TITLE
How do I change the initial current value. It is starting from 42. 

### ISSUE THREAD

**Issue by jagwanti** [jakob-grabner/Circle-Progress-View#24]
I want to use this with a timer. The timer time firstly increases from value of 42 to the the time I provided then it starts decreasing. I want to remove this initial value of 42. Not able to figure out.

**Comment by jakob-grabner** [comment]
But 42 is the answer! 
No seriously, the start value is easily changed, either by code:
```
     circleView.setValue(0);
```
or in xml:
```
     CircleProgressView:cpv_value="0"
```

**Comment by jagwanti** [comment]
Ok thanks. It worked.
