### ISSUE TITLE
Can we set the position of unit below the value?

### ISSUE THREAD

**Issue by jagwanti** [jakob-grabner/Circle-Progress-View#25]
I want to know whether we can change the position of the unit in the circle. I want to have it below the value that is displayed in the circle.

**Comment by jakob-grabner** [comment]
Just added this feature in the latest commit, please check i out and tell me if it works for you.
You can use it via:
```
compile 'com.github.jakob-grabner:Circle-Progress-View:1dd3a26c95'
```
And then you can set the unit position via xml
```
        CircleProgressView:cpv_unitPosition="bottom"
```
or code: 
```
        mCircleView.setUnitPosition(UnitPosition.BOTTOM);
```

**Comment by jagwanti** [comment]
>> compile 'com.github.jakob-grabner:Circle-Progress-View:1dd3a26c95' (not working)

>>  compile 'com.github.jakob-grabner:Circle-Progress-View:v1.2.6' (used this )
mCircleView.setUnitPosition(UnitPosition.BOTTOM);

not working compile error . :(

**Comment by jakob-grabner** [comment]
The unit position can't work with v1.2.6 because it is not included in the latest stable release. 

please try:

````
compile 'com.github.jakob-grabner:Circle-Progress-View:-SNAPSHOT'
````

**Comment by jagwanti** [comment]
Yupp it is working fine. Thanks a lot. You can update the version. :) :+1: 
when the version will be updated, I will close this thread.
