### ISSUE TITLE
bar color is not changing it showing default bar but rim is changing

### ISSUE THREAD

**Issue by jansHS** [jakob-grabner/Circle-Progress-View#28]
xml:-
  <at.grabner.circleprogress.CircleProgressView
        android:id="@+id/circleView"
        android:layout_width="75dp"
        android:layout_height="75dp"
        android:layout_marginTop="@dimen/dimen8"
        android:layout_marginLeft="14dp" />

//rcolo=#6CBD50
//bcolo=#D26911
mCircle2.setRimColor(Color.parseColor(rcolo));
        mCircle2.setBarColor(Color.parseColor(bcolo));

is my code is correct?

**Comment by jakob-grabner** [comment]
Your code is correct, this was a bug in a previous version, it is already fixed (see #27). But i forgot to draft a new release. Did it just now, please try out the latest release 1.2.8.

**Comment by jansHS** [comment]
thanks man.. i got it
