### ISSUE TITLE
unit symbol  not visible in v 1.2.8

### ISSUE THREAD

**Issue by 14122jansHS** [jakob-grabner/Circle-Progress-View#29]
<at.grabner.circleprogress.CircleProgressView
            android:id="@+id/circleView4"
            android:layout_width="84dp"
            android:layout_height="84dp"
            android:textAlignment="center"
            android:layout_marginTop="@dimen/dimen8"
            android:layout_marginLeft="@dimen/activity_horizontal_margin"
            CircleProgressView:cpv_unit="%"
            CircleProgressView:cpv_textScale="1"
            CircleProgressView:cpv_textSize="40sp"
            CircleProgressView:cpv_unitSize="30sp"
            CircleProgressView:cpv_unitPosition="right_top"
            CircleProgressView:cpv_unitScale="1"
            CircleProgressView:cpv_unitColor="@color/colorPrimary"
            CircleProgressView:cpv_showUnit="true"
            />
code using in java
    int fval=Integer.parseInt(bvalu)*10;
        mCircle2.setMaxValue(100);
        mCircle2.setValueAnimated(fval);
        mCircle2.setUnitVisible(true);
        mCircle2.setUnitColor(Color.parseColor(bcolo));

        mCircle2.setRimColor(Color.parseColor(rcolo));
        mCircle2.setBarColor(Color.parseColor(bcolo));
        //colors of text and unit can be set via
mCircle2.setText("33");
        mCircle2.setTextColor(Color.parseColor(bcolo));
        //or to use the same color as in the gradient
       // mCircle2.setAutoTextColor(true); //previous set values are ignored
        mCircle2.setBarWidth(8);
        mCircle2.setRimWidth(8);
        mCircle2.setContourSize(0);

**Comment by jakob-grabner** [comment]
My guess is that the text size you specified is just too big, so the unit is not visible any more. Just try to not specify any text size. Then the text size is calculated automatically.
