### ISSUE TITLE
Value is not centered vertically

### ISSUE THREAD

**Issue by hexdump2002** [jakob-grabner/Circle-Progress-View#30]
I can't manage to get my value centered vertically in the progress bar. The value seems to have its pivot at the top. So, when it grows (through auto text size or manual size) its top is aligened to the middle of the progressbar center and it grows towards the half bottom part of the progress bar. I can upload pictures if needed.

xml code:

```
<at.grabner.circleprogress.CircleProgressView
                android:id="@+id/circleView"
                android:layout_width="100"
                android:layout_height="100"
                android:layout_centerInParent="true"

                app:cpv_value="10"
                app:cpv_maxValue="100"
                app:cpv_barColor="@color/main_screen_progressbar_rim_fg_color"
                app:cpv_rimColor="@color/main_screen_progressbar_rim_bg_color"
                app:cpv_textColor="#FFFFFF"
                app:cpv_unitColor="#FFFFFF"
                app:cpv_spinColor="@color/main_screen_progressbar_rim_fg_color"
                app:cpv_barWidth="10dp"
                app:cpv_rimWidth="10dp"
                app:cpv_contourSize="0dp"
                app:cpv_autoTextSize="true"
                app:cpv_seekMode="true"
                app:cpv_unit="%"
                app:cpv_unitPosition="right_bottom"
                app:cpv_unitScale="1"
                app:cpv_textScale="1"
                app:cpv_showUnit="true"/>
```

**Comment by hexdump2002** [comment]
![screen shot 2015-12-03 at 12 15 03](https://cloud.githubusercontent.com/assets/7756851/11559236/8b454a5c-99b7-11e5-869e-6892bca99b5a.png)

**Comment by hexdump2002** [comment]
Ok, I have noticied this problem is not seen when deploying. I was just checking the android layout editor previsualization. My fault...

**Comment by jakob-grabner** [comment]
Hi, first thanks for using my library. This is what i thought. For some reason the preview in Android Studio is not correct. I once debugged it and it turned out that the measure text function does not return correct results in the preview in android studio. I'm afraid there is nothing i can do about this. 
But as you figured out, it's fine on the device :)

**Comment by hexdump2002** [comment]
Thank you very mucho for such a great progressbar. Really optimizable. Anyway there is something I'm missing right now. It is, the possibility of adding a text below the value. This could serve as a semantic caption for the value.

Cheers.

**Comment by jakob-grabner** [comment]
Jep that could be useful. Not sure how this would work with `UnitPosition.BOTTOM`. Anyway, if I ignore this, it shouldn't be too much work. I'll add it if I can make time :)

**Comment by LyCharlie** [comment]
why there is no left or right value, I means if I just want the unit center vertical ,what should I do?
