### ISSUE TITLE
Allow access to `mCenter`, `mXContour` to allow extensions

### ISSUE THREAD

**Issue by capitanbatata** [jakob-grabner/Circle-Progress-View#32]
I would like to extend `CircleProgressView` so that only touch events *on* the outer bar are handled by this view. This allows to add buttons on the center that also control the values on the bar. For instance think of a timer with a `-` and `+` buttons.

However `mCenter` and `mXContour` are private attributes with no "getters". It'd be nice to have these attributes as protected (so that they can be accessed by child classes), or to have "getter" methods.

**Comment by jakob-grabner** [comment]
I'm not sure, but I think it also should work if you just place ordinary buttons above the view. Then the buttons should "steal" the focus from the `CircleProgressView`. But some getters won't hurt either. However i can't find `mXContour` which member do you mean?

**Comment by capitanbatata** [comment]
I meant `mCircleInnerContour` and `mCircleOuterContour` I was just being lazy :P 

You are quite right to point out that overlaying buttons on this view may solve the problem. However I can think of some situations where this may be inconvenient:
  0. there is a list of clickable items inside the circle (the case I'm working on), and as the user scrolls the list, the items should be hidden under the progress bar.
  1. The user might click slightly outside the buttons, causing sudden changes in the values.

I just finished implementing the overriden version of the `onTouchEvent` method, and it looks as follows:

      @Override
    public boolean onTouchEvent(MotionEvent event) {
        Log.d(TAG, "onTouchEvent @(x, y) = " + event.getX() + ", " + event.getY());

        float distance = (float) Math.sqrt(
                Math.pow(circleCenter.x - event.getX(), 2) +
                Math.pow(circleCenter.y - event.getY(), 2)
        );

        if (innerRadius <= distance && distance <= outerRadius) {
            return super.onTouchEvent(event);
        } else {
            Log.d(TAG, "touch event occurred outside the circle.");
            return false;
        }
    }

I did some kludges to get the inner and outer radius: override and duplicate the `onSizeChanged` method. But this could be avoided if it is possible to get the `mCircleInnerContour` and `mCircleOuterContour` values.

**Comment by jakob-grabner** [comment]
I see. Are protected getter ok? I don't want to mess up the View with even more getter/setter that make no (not much?) sense without subclassing it...

**Comment by capitanbatata** [comment]
Sure. I don't know what is best for your design,  but protected getters should do :)

**Comment by capitanbatata** [comment]
Protected attributes (members) is also an option..

**Comment by jakob-grabner** [comment]
Here you go. Just use the snapshot version till the next release.
`compile 'com.github.jakob-grabner:Circle-Progress-View:-SNAPSHOT'`

**Comment by capitanbatata** [comment]
Thanks (for providing this library, and for the update ;)).
