### ISSUE TITLE
Show decimals number ?

### ISSUE THREAD

**Issue by hoangnguyenkal** [jakob-grabner/Circle-Progress-View#33]
Hello, this is a great library. I like it. Thanks for your hard work. Can I ask how to show decimals number ?
Ex: I set max value to "10" and I want to show current value is "6.8". I have tried, but it show "68" not "6.8".

**Comment by jakob-grabner** [comment]
Hi, this was not possible until now. Now it is possible to set a custom decimal format. Either via code:
`mCircleView.setDecimalFormat(new DecimalFormat("0.0"));`
or xml
`CircleProgressView:cpv_decimalFormat="0.0"`

you can try it out by using the snapshot version:
`compile 'com.github.jakob-grabner:Circle-Progress-View:-SNAPSHOT'`

**Comment by hoangnguyenkal** [comment]
Thank you for your hard work. I have tried. It runs well if I set max value is 100. But if I set max value is 10, it shows not the correct value.

**Comment by jakob-grabner** [comment]
It should work, but I think your problem is that you use the CirlceView in "PercentMode".
Per default the current percentage of the current value in respect to the max value is shown. In order to show the current value, just set the text mode. Via code:
`mCircleView.setTextMode(TextMode.VALUE);`
via xml
`CircleProgressView:cpv_textMode="Value"`

**Comment by hoangnguyenkal** [comment]
Ok, I understood. Thank you again.

**Comment by LOG-TAG** [comment]
Thanks all features ,  
```
mCircleView1.setTextMode(TextMode.VALUE);  //min1 max5 value case
 mCircleView1.setValueAnimated(04, 1500); 
```
![img_20160708_120546](https://cloud.githubusercontent.com/assets/1190344/16679332/71dad160-4504-11e6-804c-1ed4f6e31425.jpg)

Unfortunately single digit number displayed with larger text size comparing to 2 digit numb !! any fix available to display at least 04 or recentered 4 like two digit number text size?

**Comment by jakob-grabner** [comment]
Do you still have issues, or is everything fixed for you right now?

**Comment by LOG-TAG** [comment]
@jakob-grabner Solved!!! I got the solution after commenting !! Thanks again for such a complete Library! !

**Comment by Swapnil1234567** [comment]
I want to show value in percentage with percentage sign and some text inside circle. How should i achieve it?
