### ISSUE TITLE
Sets default bar color instead of new single color

### ISSUE THREAD

**Issue by tigransahakyan** [jakob-grabner/Circle-Progress-View#34]
there is a bug in setBarColor(int color) method of CircleProgressView.
in if/else statement in line 524 should be:
this.mBarColors.length == 1
instead of:
this.mBarColors.length == 0

**Comment by jakob-grabner** [comment]
Hi, sry but i can't see a bug here. The current code works as follows: 
```java
if(this.mBarColors.length > 1)
// multiple colors given -> use gradient
else if(this.mBarColors.length == 1)
// single color given -> use single color
else
// no color given  -> use default
```
