### ISSUE TITLE
Starting point

### ISSUE THREAD

**Issue by LinkOut** [jakob-grabner/Circle-Progress-View#35]
Hi, nice Lib, is it possibile to set the start point of loading bar from top to left?

**Comment by jakob-grabner** [comment]
Hi,
not especially for the loading, but you can define the overall start angle. So for the loading bar as well as the value bar. 
XML:
```
CircleProgressView:cpv_startAngle="180"
```

Code:
```
circleView.setStartAngle(180);
```

**Comment by LinkOut** [comment]
Ok, thanks, and is it possibile to add a custom view at the end of the loading bar?

**Comment by jakob-grabner** [comment]
No, for what would you need it?

**Comment by LinkOut** [comment]
Actually i need one at the start of progress, so mark more the start point.

**Comment by LinkOut** [comment]
Hi, is there a way to hide "internal" contour?

**Comment by jakob-grabner** [comment]
Just set size to 0.

**Comment by LinkOut** [comment]
No i mean, hide internal but show external. But is ok. 

I ve set : CircleProgressView:cpv_maxValue="9"

And i try to: .setValueAnimated(0, 4, 1000);  //This goes to 44?

And, is possibile to set custom font inside?

Thanks a lot.

**Comment by jakob-grabner** [comment]
Ah ok, no, the contour is either visible inside and outside the circle or not at all at the moment.

Per default the current percentage of the current value in respect to the max value is shown. In order to show the current value, just set the text mode. Via code:
`mCircleView.setTextMode(TextMode.VALUE);`
via xml
`CircleProgressView:cpv_textMode="Value"`

Custom font

```java
        //custom typeface
        Typeface font = Typeface.createFromAsset(getAssets(), "fonts/ANDROID_ROBOT.ttf");
        mCircleView.setTextTypeface(font);
        mCircleView.setUnitTextTypeface(font);
```

**Comment by LinkOut** [comment]
Awesome! Thanks alot!
