### ISSUE TITLE
Support interpolators other than AccelerateDecelerateInterpolator

### ISSUE THREAD

**Issue by MikeSoukup** [jakob-grabner/Circle-Progress-View#41]
It would be nice to use other interpolators (specifically LinearInterpolator).  I can make the change if you'll accept a pull request.

**Comment by jakob-grabner** [comment]
Hi, that should not be that much of a problem. I included two setters in the latest commit. I have not tested it yet, so please let me know if it works. 
You can test it by using the latest snapshot version
```
 compile 'com.github.jakob-grabner:Circle-Progress-View:-SNAPSHOT'
```

**Comment by MikeSoukup** [comment]
It's exactly what I was looking for.  Thanks for the quick response.

**Comment by MikeSoukup** [comment]
Any chance you'll put out a release soon with this fix?  The SNAPSHOT version is no longer available and I'd like to avoid building it locally.

**Comment by jakob-grabner** [comment]
Done.
