### ISSUE TITLE
how can i set the  gradient from up to 4 colors

### ISSUE THREAD

**Issue by TimAimee** [jakob-grabner/Circle-Progress-View#49]
i can't find the way to set the gradient from up to 4 colors, how can i do it?

**Comment by jakob-grabner** [comment]
The set bar color methods of the circle view expectes one or more colors, just pass 4 colors to get a gradient with 4 colors. 
`void setBarColor(@ColorInt int... barColors)
`
If want to define the gradient in xml, this can be done with up to 4 colors. Just set the following attributes:
`cpv_barColor, cpv_barColor1,cpv_barColor2,cpv_barColor3`

If you have any troubles please let me know.

**Comment by TimAimee** [comment]
@jakob-grabner thanks!
