### ISSUE TITLE
if textSize is set, unit text is positioned above circle

### ISSUE THREAD

**Issue by adennie** [jakob-grabner/Circle-Progress-View#5]
If the textSize attribute is set in xml, the unit text is mis-positioned; it ends up being above the circle (it's hard to see because it's cut off, but you can see the bottom pixel or so).  For example, if I add 

        CircleProgressView:textSize="48dp"

in ExampleApp's activity_main.xml, and then run it, I get this:

![image](https://cloud.githubusercontent.com/assets/1521215/9284711/21782fde-42ac-11e5-8904-945a81021394.png)

I assume the problem is somewhere in here, but I'm having trouble following it...

            if (update) {
                //calc unit text position
                mUnitBounds = new RectF(mOuterTextBounds.left + (mOuterTextBounds.width() * (1 - mRelativeUniteSize) * relativeGap), mOuterTextBounds.top, mOuterTextBounds.right, mOuterTextBounds.bottom);
                mUnitTextPaint.setTextSize(calcTextSizeForRect(mUnit, mUnitTextPaint, mUnitBounds) * mUnitScale);
                mUnitBounds = getTextBounds(mUnit, mUnitTextPaint, mUnitBounds);
                //move unite to top of text
                float dy = mActualTextBounds.top - mUnitBounds.top;
                mUnitBounds.offset(0, dy);
            }

**Comment by jakob-grabner** [comment]
You are right there was certainly an issue. The latest commit should fix this issue. I tested the units only with auto text size on. Now if you set the text size, you also have to set the unit size.

**Comment by adennie** [comment]
Awesome, thanks for the quick fix!

- Andy
