### ISSUE TITLE
Show decimal value

### ISSUE THREAD

**Issue by simoneluconi** [jakob-grabner/Circle-Progress-View#50]
It's possibile to add the possibility to show decimal value like in [this library](https://github.com/falahati/CircularProgressBar)?

![](https://raw.githubusercontent.com/falahati/CircularProgressBar/master/screenshot.gif)

**Comment by jakob-grabner** [comment]
Hi, no this is not possible at the moment. Feel free to make a pull request :).

But what you can do is to show a decimal value as seen below by doing the following: 

        mCircleView.setTextMode(TextMode.VALUE);
        mCircleView.setValue(0.5f);
        mCircleView.setDecimalFormat(new DecimalFormat("0.00"));

![float](https://cloud.githubusercontent.com/assets/7100572/21547731/2eee3a50-cde8-11e6-8eaa-3e5b26464a3b.jpg)
