### ISSUE TITLE
How to use gradient color

### ISSUE THREAD

**Issue by MansoorJafari** [jakob-grabner/Circle-Progress-View#54]
Hi Mr.Jakon

How to use gradient color for circle_progress?

Thanks.

**Comment by khalid-mahmood** [comment]
The set bar color methods of the circle view expectes one or more colors, just pass 4 colors to get a gradient with 4 colors. 
void setBarColor(@ColorInt int... barColors) 
If want to define the gradient in xml, this can be done with up to 4 colors. Just set the following attributes:
cpv_barColor, cpv_barColor1,cpv_barColor2,cpv_barColor3

@MansoorJafari
