### ISSUE TITLE
How can I accomplish this style? [Img inside]

### ISSUE THREAD

**Issue by palla89** [jakob-grabner/Circle-Progress-View#63]
Hi, I didn't find any property regarding this style represented in homepage. How can I do this?
![big](https://cloud.githubusercontent.com/assets/12301205/20564890/731f92d4-b18f-11e6-9b76-75a818f17254.png)

Thanks for your answers!

**Comment by bjdupuis** [comment]
What precisely about it are you having difficulty with? If you mean the "blocks", try setting the cpv_blockCount attribute to 18 to get this appearance.
