### ISSUE TITLE
'cpv_unitPosition' attribute has the same value for enums: 'right_bottom' and 'right_top'

### ISSUE THREAD

**Issue by inman17** [jakob-grabner/Circle-Progress-View#64]
src/main/res/values/attrs.xml

        <attr name="cpv_unitPosition" format="enum">
            <enum name="top" value="0" />
            <enum name="bottom" value="1" />
            <enum name="left_top" value="2" />
            <enum name="right_top" value="3" />
            <enum name="left_bottom" value="2" />
            <enum name="right_bottom" value="3" />
        </attr>

Below enums:
- "right_top" and "right_bottom"
- "left_top" and "left_bottom"
have the same values. 

I believe that's the reason why "right_bottom" position is not working as expected when using xml attributes ;)

**Comment by unclebanana** [comment]
Same issue to me
