### ISSUE TITLE
Bug with pointer

### ISSUE THREAD

**Issue by leshka890** [jakob-grabner/Circle-Progress-View#66]
Bug with pointer. Pointer always in center view after inflate view before touch.
https://www.dropbox.com/s/vxvmm9z586dnzlm/Screenshot_20161215-113431.png?dl=0 - this is screenshot.
Device Samsung Galaxy S7. 

I use this solution in onCreate:
//            new Handler().postDelayed(new Runnable() {
//                @Override
//                public void run() {
//                        mCircleSeekBar.invalidate();
//                }
//            }, 70);

but is not good decision

**Comment by jakob-grabner** [comment]
could you please elaborate the problem

**Comment by jakob-grabner** [comment]
Closed because of inactivity.
