### ISSUE TITLE
Unable to compile via Gradle

### ISSUE THREAD

**Issue by libern** [jakob-grabner/Circle-Progress-View#8]
Hi, I tried following:

    compile 'com.github.jakob-grabner:Circle-Progress-View:a9ac80c39b'

OR

    compile 'com.github.jakob-grabner:Circle-Progress-View:1.1'

But, it comes error says:

    Error:(45, 13) Failed to resolve: com.github.jakob-grabner:Circle-Progress-View:a9ac80c39b

May you suggest the correct way to install this library through gradle?

**Comment by jakob-grabner** [comment]
Please make sure that you added the jitpack repo.
repositories {
    // ...
    maven { url "https://jitpack.io" }
}

**Comment by nikoker** [comment]
Hey I have the same problem and I have already added the maven repository.

**Comment by libern** [comment]
Awesome! Solved.


@nikoker you should put this mavan(xx) under another gradle file. I succeeded.

**Comment by jakob-grabner** [comment]
It works fine for me. 
The gradle file of the entire project looks as follows: 
```
 buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

And the gradle file for the app module: 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.example.jakobgrabner.myapplication"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.github.jakob-grabner:Circle-Progress-View:v1.2'
}

You do not need to include the lib into the settings.gradle.

Please let me know if this fixes your issues.

**Comment by nikoker** [comment]
It works fine, thanks.

I made a mistake and added the maven repository to buildscript repositories. When I added it to allprojects, it worked fine.

Good work btw.

**Comment by anas-ali** [comment]
Hi,
I am facing this issue when I am compiling Circle-Progress-View in my .gradle file.
**Error:Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/com/github/jakob-grabner/Circle-Progress-View/v1.3/Circle-Progress-View-v1.3.pom'. Received status code 409 from server: Conflict**

I have added snapshots because am using realm
maven {url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'}

I have added 
maven { url 'https://jitpack.io' } 

But still facing issue in adding it in my project
