### ISSUE TITLE
Clickable  CircleProgressView

### ISSUE THREAD

**Issue by TalalAlenzi** [jakob-grabner/Circle-Progress-View#85]
Hello,
I tried to mProgress.setClickable(false), but it didnt work !!.. I do not want the user click on it ..

Any ideas about this issue ..

**Comment by Shouheng88** [comment]
how about add ' app:cpv_seekMode="true"' to the value deined in the xml?

**Comment by janegrytsenko** [comment]
@TalalAlenzi Hi! Have you solved this issue?

**Comment by TalalAlenzi** [comment]
Yes, I solved this issue as Shouheng88 said.
