### ISSUE TITLE
Different value for progress ring and for value in center

### ISSUE THREAD

**Issue by coanag** [jakob-grabner/Circle-Progress-View#87]
While testing this component, show the value in center is calculated with MaxValue and the Value set by me. Is it possible to set the value shown in center wioutout being calculated?
For example i have 10 days remaining in a range of 100. I want to show in center 10 and in the ring progress  90% filed.
Thank you in advance.

**Comment by twogood** [comment]
Use setText(text)
You need also set the TextMode to TextMode.TEXT to see the text.
