### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by AndreiD** [jakob-grabner/Circle-Progress-View#92]
hello, can we get some info about the license of this project ? thanks

**Comment by jakob-grabner** [comment]
This project is licenced by the MIT license. See https://github.com/jakob-grabner/Circle-Progress-View/blob/master/LICENSE

**Comment by AndreiD** [comment]
Thanks man, I didn't noticed it

**Comment by Phakawanwijittra** [comment]
How can do?
